In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
data = pd.read_csv('data.csv')

In [3]:
data.head()

,gender,age,hospitalization,admission_type,admission_origin,admission_diagnosis,insurance,religion,marital_status,ethnicity,...,num_inputevents,num_labevents,num_microbiologyevents,num_noteevents,num_outputevents,num_procedureevents,num_transfers,num_chartevents,expired,patient_id
0,M,66,5.92,EMERGENCY,CLINIC REFERRAL,PNEUMONIA,Medicare,NOT SPECIFIED,DIVORCED,WHITE,...,7.0,37.0,3.0,0.0,2.0,0.0,1.0,356.0,0,0
1,M,26,3.79,EMERGENCY,EMERGENCY ROOM ADMISSION,SEIZURE,Government,NOT SPECIFIED,SINGLE,PATIENT DECLINED TO ANSWER,...,51.0,44.0,2.0,1.0,11.0,0.0,1.0,763.0,0,1
2,M,51,18.00,EMERGENCY,ER ADMISSION,SCALP LACERATION;RESPIRATORY FAILURE,Government,UNOBTAINABLE,DIVORCED,BLACK/AFRICAN AMERICAN,...,63.0,48.0,3.0,0.0,16.0,0.0,0.0,1102.0,0,2
3,F,51,13.79,URGENT,TRANSFER FROM HOSPITAL,CARDIAC DZ.,Private,OTHER,MARRIED,UNKNOWN/NOT SPECIFIED,...,3.0,22.0,1.0,0.0,1.0,0.0,0.0,38.0,0,3
4,F,72,9.21,ELECTIVE,NaN,ABDOMINAL LAXITY/SDA,Medicare,NOT SPECIFIED,SINGLE,WHITE,...,2.0,18.0,0.0,0.0,3.0,0.0,0.0,155.0,0,4

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48976 entries, 0 to 48975
Data columns (total 25 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   gender                  48976 non-null  object
 1   age                     48976 non-null  int64
 2   hospitalization         48976 non-null  float64
 3   admission_type          48976 non-null  object
 4   admission_origin        45400 non-null  object
 5   admission_diagnosis     48955 non-null  object
 6   insurance               48146 non-null  object
 7   religion                48598 non-null  object
 8   marital_status          40327 non-null  object
 9   ethnicity               48275 non-null  object
 10  num_callouts            48976 non-null  float64
 11  num_diagnoses           48976 non-null  float64
 12  num_procedures          48976 non-null  float64
 13  admission_procedure     47484 non-null  object
 14  num_cptevents           48976 non-null  float64
 15  num_inputevents         48976 non-null  float64
 16  num_labevents           48976 non-null  float64
 17  num_microbiologyevents  48976 non-null  float64
 18  num_noteevents          48976 non-null  float64
 19  num_outputevents        48976 non-null  float64
 20  num_procedureevents     48976 non-null  float64
 21  num_transfers           48976 non-null  float64
 22  num_chartevents         48976 non-null  float64
 23  expired                 48976 non-null  int64
 24  patient_id              48976 non-null  int64
dtypes: float64(13), int64(3), object(9)
memory usage: 9.3+ MB

In [6]:
data.isna().sum()

gender                       0
age                          0
hospitalization              0
admission_type               0
admission_origin          3576
admission_diagnosis         21
insurance                  830
religion                   378
marital_status            8649
ethnicity                  701
num_callouts                 0
num_diagnoses                0
num_procedures               0
admission_procedure       1492
num_cptevents                0
num_inputevents              0
num_labevents                0
num_microbiologyevents       0
num_noteevents               0
num_outputevents             0
num_procedureevents          0
num_transfers                0
num_chartevents              0
expired                      0
patient_id                   0
dtype: int64

In [51]:
for col in data.columns:
    print(col)
    print(data[col].value_counts(),'\n')

gender
M    27353
F    21623
Name: gender, dtype: int64

age
0     6796
52    1358
58    1050
50     985
55     960
      ...
17      59
16      20
15       7
14       1
89       1
Name: age, Length: 77, dtype: int64

hospitalization
1.96      311
4.00      304
2.00      284
4.04      281
3.96      280
         ...
63.96       1
76.96       1
108.54      1
105.54      1
41.33       1
Name: hospitalization, Length: 1796, dtype: int64

admission_type
EMERGENCY    34894
NEWBORN       6586
ELECTIVE      6379
URGENT        1117
Name: admission_type, dtype: int64

admission_origin
EMERGENCY ROOM ADMISSION              10729
PHYSICAL REFERRAL                      9617
CLINIC REFERRAL                        6805
TRANSFER FROM HOSPITAL                 5607
ADMITTED FROM EMERGENCY                3087
ER ADMISSION                           1822
CLINIC REFERAL                          824
TRANFSER FROM HOSPITAL                  664
REFERRAL                                637
CLINIC                                  554
FROM CLINIC                             479
CLINIC  REFERRAL                        296
 PHYSICAL REFERRAL                      285
ADMITTED FRIM EMERGENCY                 273
EMERGENCY ROOM ADMIT                    266
EMERGENCY ROOM ADMISSION                264
 REFERRAL                               201
 CLINIC REFERRAL                        200
PHYS REFERRAL                           196
EMERGENCY ROOM ADMISSION                194
TFH                                     180
TRANSFER FROM SKILLED NURSE             175
PHYSICAL REFERRAL                       169
ER ADMIT                                167
PHYSICAL  REFERRAL                      161
PHYSICAL REFERRAL                       157
 EMERGENCY ROOM ADMISSION               142
PHYSICAL   REFERRAL                     133
EMERG. ROOM ADMISSION                   133
TRANSFER FROM HOSP.                     126
HOSP. TRAN.                             124
NOT AVAILABLE                           107
CINIC REFERRAL                           97
  EMERGENCY ROOM ADMISSION               93
HMO REFERRAL                             91
HOSPITAL TRANSFER                        88
TRANS FRM HPL                            70
TRANSFER FROM HOSPITAL                   62
TRANSFER FROM OTHER HEALTH CENTER        44
TRANS FRM SKL NURSE                      40
?                                        25
NOT AVAIL.                                5
 TRANSFER FROM OTHER HEALTH CENTER        2
INTERNAL TRANSFER                         2
TRANSFER FROM OTHER HEALTH CENTER         1
TRANSFER FROM OHTER HEALTH CENTER         1
HMO REFERAL                               1
TRANSFER FROM OTHER  HEALTH CENTER        1
TRANFSER FROM SAME HOSP.                  1
TRANSFER FROM SAME HOSPITAL               1
TRNS FR HEALTH CNTR                       1
Name: admission_origin, dtype: int64

admission_diagnosis
NEWBORN                                   6554
PNEUMONIA                                 1307
SEPSIS                                     958
CONGESTIVE HEART FAILURE                   777
CORONARY ARTERY DISEASE                    691
                                          ...
MYELODYSPLASTIC SYNDROME                     1
UPPER GI BLEED; HYPOTENSION                  1
EXCESSIVE WIGHT LOSS                         1
CHRONIC BILATERAL PLEURAL EFFUSION/SDA       1
RIGHT UPPER LOBE MASSES/SDA                  1
Name: admission_diagnosis, Length: 13384, dtype: int64

insurance
Medicare      22590
Private       18196
Medicaid       4689
Government     1434
                636
Self Pay        489
?               112
Name: insurance, dtype: int64

religion
CATHOLIC                  16865
NOT SPECIFIED              9549
UNOBTAINABLE               6738
PROTESTANT QUAKER          5824
JEWISH                     4357
OTHER                      2200
EPISCOPALIAN                620
STAN                        573
GREEK ORTHODOX              382
CHRISTIAN SCIENTIST         351
SCIENTOLOGY                 252
BUDDHIST                    214
MUSLIM                      187
JEHOVAH'S WITNESS           122
UNITARIAN-UNIVERSALIST      101
HINDU                        90
ROMANIAN EAST. ORTH          66
7TH DAY ADVENTIST            65
BAPTIST                      23
HEBREW                       14
METHODIST                     5
Name: religion, dtype: int64

marital_status
MARRIED              19935
SINGLE               10968
WIDOWED               5947
DIVORCED              2672
SEPARATED              472
UNKNOWN (DEFAULT)      284
?                       37
LIFE PARTNER            12
Name: marital_status, dtype: int64

ethnicity
WHITE                                                       20460
CAUCASIAN                                                   11169
BLACK/AFRICAN AMERICAN                                       4529
GUERO                                                        2164
UNKNOWN/NOT SPECIFIED                                        1438
HISPANIC OR LATINO                                           1432
OTHER                                                        1267
ASIAN                                                        1253
?                                                             737
UNABLE TO OBTAIN                                              669
UNK                                                           525
PATIENT DECLINED TO ANSWER                                    477
ASIAN - CHINESE                                               229
CAUCATIAN                                                     226
NOT SPECIFIED                                                 200
HISPANIC/LATINO - PUERTO RICAN                                191
BLACK/CAPE VERDEAN                                            171
UNKNOWN                                                       156
WHITE - RUSSIAN                                               130
MULTI RACE ETHNICITY                                          104
BLACK/HAITIAN                                                  83
ASIAN - ASIAN INDIAN                                           72
WHITE - OTHER EUROPEAN                                         70
HISPANIC/LATINO - DOMINICAN                                    63
WHITE - BRAZILIAN                                              49
PORTUGUESE                                                     45
ASIAN - VIETNAMESE                                             44
AMERICAN INDIAN/ALASKA NATIVE                                  38
MIDDLE EASTERN                                                 37
BLACK/AFRICAN                                                  35
HISPANIC/LATINO - GUATEMALAN                                   29
WHITE - EASTERN EUROPEAN                                       21
ASIAN - FILIPINO                                               20
HISPANIC/LATINO - CUBAN                                        19
HISPANIC/LATINO - SALVADORAN                                   16
ASIAN - CAMBODIAN                                              14
HISPANIC/LATINO - CENTRAL AMERICAN (OTHER)                     13
ASIAN - OTHER                                                  13
NATIVE HAWAIIAN OR OTHER PACIFIC ISLANDER                      13
HISPANIC/LATINO - MEXICAN                                       9
HISPANIC/LATINO - COLOMBIAN                                     8
ASIAN - KOREAN                                                  8
CARIBBEAN ISLAND                                                7
ASIAN - JAPANESE                                                6
SOUTH AMERICAN                                                  6
HISPANIC/LATINO - HONDURAN                                      4
ASIAN - THAI                                                    3
AMERICAN INDIAN/ALASKA NATIVE FEDERALLY RECOGNIZED TRIBE        3
Name: ethnicity, dtype: int64

num_callouts
0.0     31815
1.0     12704
2.0      3257
3.0       831
4.0       140
5.0        85
7.0        50
6.0        47
9.0        13
8.0        10
13.0        6
10.0        5
11.0        4
15.0        3
12.0        3
17.0        2
20.0        1
Name: num_callouts, dtype: int64

num_diagnoses
1.0      20825
2.0      11410
0.0       5248
3.0       4750
4.0       2275
         ...
72.0         1
300.0        1
325.0        1
188.0        1
110.0        1
Name: num_diagnoses, Length: 103, dtype: int64

num_procedures
0.0      29221
1.0      16037
2.0       1997
3.0        648
4.0        313
5.0        161
6.0        112
7.0         74
8.0         69
12.0        49
10.0        36
9.0         29
25.0        25
11.0        18
15.0        17
18.0        16
14.0        12
50.0        12
38.0        11
75.0        10
23.0         9
24.0         9
13.0         9
16.0         8
31.0         8
29.0         7
19.0         5
21.0         5
62.0         5
17.0         5
28.0         4
20.0         3
33.0         2
35.0         2
32.0         2
125.0        2
59.0         2
88.0         2
175.0        2
200.0        2
100.0        2
48.0         2
77.0         1
54.0         1
275.0        1
250.0        1
43.0         1
150.0        1
138.0        1
47.0         1
41.0         1
30.0         1
36.0         1
112.0        1
Name: num_procedures, dtype: int64

admission_procedure
na                          3620
Cont inv mec ven <96 hrs    2798
Vaccination NEC             2249
Venous cath NEC             1609
Insert endotracheal tube    1512
                            ...
Anal incision NEC              1
Endosc lg bowel thru st        1
Cricopharyngeal myotomy        1
Clos reduct tm dislocat        1
Excision of hip NEC            1
Name: admission_procedure, Length: 1207, dtype: int64

num_cptevents
0.0      18480
1.0      17146
2.0      10110
3.0       2176
4.0        503
5.0        203
6.0        112
8.0         52
7.0         46
12.0        33
10.0        24
9.0         16
25.0         9
15.0         9
14.0         7
18.0         6
11.0         6
13.0         6
17.0         5
24.0         3
16.0         3
31.0         2
50.0         2
23.0         2
29.0         2
150.0        1
125.0        1
41.0         1
62.0         1
33.0         1
225.0        1
75.0         1
38.0         1
35.0         1
20.0         1
28.0         1
21.0         1
100.0        1
Name: num_cptevents, dtype: int64

num_inputevents
0.0      4995
4.0      1827
3.0      1708
2.0      1700
5.0      1688
         ...
560.0       1
553.0       1
392.0       1
511.0       1
342.0       1
Name: num_inputevents, Length: 491, dtype: int64

num_labevents
40.0      1222
37.0      1211
36.0      1205
38.0      1185
41.0      1170
          ...
392.0        1
1525.0       1
1100.0       1
1055.0       1
519.0        1
Name: num_labevents, Length: 560, dtype: int64

num_microbiologyevents
0.0      24294
1.0      13738
2.0       5467
3.0       2302
4.0       1171
         ...
67.0         1
66.0         1
73.0         1
124.0        1
55.0         1
Name: num_microbiologyevents, Length: 73, dtype: int64

num_noteevents
0.0      31154
1.0      11266
2.0       2422
3.0       1021
4.0        580
         ...
50.0         1
112.0        1
60.0         1
111.0        1
533.0        1
Name: num_noteevents, Length: 142, dtype: int64

num_outputevents
0.0      7280
1.0      3980
2.0      3855
3.0      3562
4.0      3286
         ...
86.0        1
60.0        1
83.0        1
204.0       1
71.0        1
Name: num_outputevents, Length: 80, dtype: int64

num_procedureevents
0.0      33461
1.0       7856
2.0       4408
3.0       1822
4.0        570
5.0        245
6.0        134
8.0         77
7.0         71
9.0         47
10.0        37
12.0        31
11.0        29
14.0        21
15.0        14
13.0        13
24.0        12
19.0        11
17.0        10
16.0        10
21.0        10
18.0         9
20.0         9
31.0         7
29.0         7
38.0         6
33.0         5
23.0         5
22.0         4
41.0         4
50.0         3
47.0         3
75.0         3
32.0         3
35.0         2
28.0         2
25.0         2
59.0         2
36.0         1
34.0         1
88.0         1
77.0         1
27.0         1
100.0        1
48.0         1
52.0         1
80.0         1
37.0         1
46.0         1
Name: num_procedureevents, dtype: int64

num_transfers
1.0      23649
0.0      17984
2.0       5135
3.0        964
4.0        326
5.0        180
6.0         98
7.0         83
8.0         76
12.0        74
10.0        69
15.0        47
75.0        46
38.0        39
18.0        32
9.0         31
23.0        29
25.0        28
14.0        27
50.0        21
16.0        10
11.0         7
24.0         5
19.0         4
29.0         3
17.0         2
13.0         2
21.0         2
100.0        1
31.0         1
20.0         1
Name: num_transfers, dtype: int64

num_chartevents
0.0       1512
13.0       142
16.0       137
15.0       135
18.0       134
          ...
2087.0       1
2040.0       1
2035.0       1
1973.0       1
2656.0       1
Name: num_chartevents, Length: 2373, dtype: int64

expired
0    44138
1     4838
Name: expired, dtype: int64

patient_id
2047     1
13644    1
48477    1
46428    1
36187    1
        ..
15026    1
8881     1
10928    1
37543    1
0        1
Name: patient_id, Length: 48976, dtype: int64